lzc-sdk-version: 0.1
name: symphony
package: me.stringke.app.symphony
version: 1.0.0
description:
license: https://choosealicense.com/licenses/mit/
homepage:
author: stringke
unsupported_platforms:
  - android
  - ios
  - tvos
application:
  subdomain: symphony
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  routes:
    - /=http://tolgee.me.stringke.app.tolgee.lzcapp:8080/
  ingress:
    - protocol: tcp
      port: 25432
      service: tolgee
services:
  tolgee:
    image: "registry.lazycat.cloud/u89208082/tolgee/tolgee:4833df5b1d1d9ae9"
    binds:
      - /lzcapp/var/data:/data
