lzc-sdk-version: 0.1
name: dagu
package: me.stringke.app.dagu
version: 1.16.0
description: 
license: https://choosealicense.com/licenses/mit/
homepage: 
author: stringke
unsupported_platforms: 
  - android
  - ios
  - tvos
application:
  subdomain: dagu
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  routes:
    - /=http://dagu.me.stringke.app.dagu.lzcapp:8080/
services:
  dagu:
    image: "registry.lazycat.cloud/u89208082/dagu-org/dagu:c0f703978604cb82"
    binds:
      - /lzcapp/var/config:/root/.config/dagu/
    entrypoint: dagu start-all
    health_check:
      test_url: http://127.0.0.1:8080
      start_period: 600s
      disable: false