lzc-sdk-version: 0.1
name: khoj
package: me.stringke.app.khoj
version: 0.9.11
description: 
license: https://choosealicense.com/licenses/mit/
homepage: 
author: stringke
unsupported_platforms: 
  - android
  - ios
  - tvos
application:
  subdomain: kotaemon
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  routes:
    - /=http://server.me.stringke.app.khoj.lzcapp:42110/
services:
  database:
    image: ankane/pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    bind:
      - /lzcapp/var/db:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
  sandbox:
    image: ghcr.io/khoj-ai/terrarium:latest
    restart: unless-stopped
  search:
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    bind:
      - /lzcapp/var/search:/etc/searxng
    environment:
      - SEARXNG_BASE_URL=http://localhost:8080/
  server:
    depends_on:
      database:
        condition: service_healthy
    image: ghcr.io/khoj-ai/khoj:latest
    restart: unless-stopped
    ports:
      - "42110:42110"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /app
    volumes:
      - khoj_config:/root/.khoj/
      - khoj_models:/root/.cache/torch/sentence_transformers
      - khoj_models:/root/.cache/huggingface
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - KHOJ_DJANGO_SECRET_KEY=secret
      - KHOJ_DEBUG=False
      - KHOJ_ADMIN_EMAIL=username@example.com
      - KHOJ_ADMIN_PASSWORD=password
      - KHOJ_TERRARIUM_URL=http://sandbox:8080
      - KHOJ_SEARXNG_URL=http://search:8080
      # - OPENAI_API_BASE=http://host.docker.internal:11434/v1/
      # - OPENAI_API_KEY=your_openai_api_key
      # - GEMINI_API_KEY=your_gemini_api_key
      # - ANTHROPIC_API_KEY=your_anthropic_api_key# - JINA_API_KEY=your_jina_api_key
      # - SERPER_DEV_API_KEY=your_serper_dev_api_key
      # - FIRECRAWL_API_KEY=your_firecrawl_api_key
      # - OLOSTEP_API_KEY=your_olostep_api_key
      # - KHOJ_NO_HTTPS=True
      # - KHOJ_DOMAIN=192.168.0.104
      # - KHOJ_DOMAIN=khoj.example.com
      - KHOJ_TELEMETRY_DISABLE=True
    entrypoint: --host="0.0.0.0" --port=42110 -vv --anonymous-mode --non-interactive
