lzc-sdk-version: 0.1
name: adguard
package: me.stringke.app.adguard
version: 0.107.55
description:
license: https://choosealicense.com/licenses/mit/
homepage:
author: stringke
unsupported_platforms:
  - android
  - ios
  - tvos
application:
  subdomain: adguard
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  routes:
    - /=http://adguard.me.stringke.app.adguard.lzcapp:3000/
  ingress:
    - protocol: tcp
      port: 53
      service: adguard
    - protocol: udp
      port: 53
      service: adguard
    - protocol: tcp
      port: 67
      service: adguard
    - protocol: udp
      port: 67
      service: adguard
    - protocol: tcp
      port: 3000
      service: adguard
    - protocol: tcp
      port: 853
      service: adguard
    - protocol: udp
      port: 784
      service: adguard
    - protocol: udp
      port: 853
      service: adguard
    - protocol: udp
      port: 8853
      service: adguard
    - protocol: tcp
      port: 5443
      service: adguard
    - protocol: udp
      port: 5443
      service: adguard
services:
  adguard:
    image: "registry.lazycat.cloud/u89208082/adguard/adguardhome:633154b8e53689a5"
    binds:
      - /lzcapp/var/work:/opt/adguardhome/work
      - /lzcapp/var/conf:/opt/adguardhome/conf
