lzc-sdk-version: 0.1
name: kotaemon
package: me.stringke.app.kotaemon
version: 0.9.11
description: 
license: https://choosealicense.com/licenses/mit/
homepage: 
author: stringke
unsupported_platforms: 
  - android
  - ios
  - tvos
application:
  subdomain: kotaemon
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  routes:
    - /=http://kotaemon.me.stringke.app.kotaemon.lzcapp:7860/
services:
  kotaemon:
    image: "registry.lazycat.cloud/u89208082/cinnamon/kotaemon:ad106702ca20aceb"
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
      - NLTK_DATA=/lzcapp/var/nltk_data
    binds:
      - /lzcapp/var/ktem_app_data:/app/ktem_app_data
    health_check:
      test_url: http://127.0.0.1:7860
      start_period: 600s
      disable: false